### PR TITLE
Add `REST::DisconnectedError` to connection errors

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by segiddins** [comment]
:+1:

**Comment by Manfred** [comment]
Do you know who is throwing this exception? I can't find a reference to in the Ruby standard library.

**Comment by neonichu** [comment]
It's defined by nap itself: https://github.com/Fingertips/nap/blob/master/lib/rest.rb#L13

**Comment by Manfred** [comment]
Ah right, wouldn't it be better to get rid of that exception entirely and just let the EOFError bubble through?

**Comment by neonichu** [comment]
IDK, if you think that's the better fix, I can change the PR to do that.

**Comment by Manfred** [comment]
That would be great.

**Comment by Manfred** [comment]
@neonichu I took the liberty of doing a bit of housekeeping in #10 so that supersedes this PR. Thanks for your time! Would you mind take a look at that PR to see if you see anything weird?

**Pull request closed without merging**
